bbaseURL = "https://wxiaote.github.io" 
title = "Wxiaote`s Blog" 
languageCode = "zh-cn" # 语言

hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
#theme = "LeaveIt" # 主题 
theme = "hexo-theme-yilia" # 主题 
paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt
googleAnalytics = "" # Google 统计 id
preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"


[menu]
  [[menu.main]]
    name = "随笔"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4
	
	
	
	
[params]
    since = 2016
    author = "Wxiaote"                          # Author's name
    avatar = "https://github.com/Wxiaote/cloudimg/blob/master/wxiaote/39849860.png?raw=true"           
    subtitle = "心跳不止，代码不止"                  # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统
    google_verification = ""
    description = "Wxiaote 的个人博客" # (Meta) 描述
    keywords = " Gopher, Linux, C/C++, 云计算, 存储" # site keywords
    beian = ""
    baiduAnalytics = ""
	  googleAnalytics = "UA-104502658-2" # Google 统计 id
	
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'




[params.social]
    GitHub = "Wxiaote"
    Twitter = "wxiaote"
    Email   = "ggzxiaote@gmail.com"
    #Instagram = "xxoo"
    #Wechat = "/images/me/wechat.jpg"  # Wechat QRcode image
    Facebook = "xiao.te.549"
    #Telegram = "xxoo"
    #Dribbble = "xxoo"
    #Medium = "xxoo"





[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "2bd15ea625f5f1814910" # Your client ID
    clientSecret = "ee8be25bb6a49574013a9d2107dff1ad1630574f" # Your client secret
    repo = "wxiaote.github.io" # The repo to store comments
    owner = "Wxiaote" # Your GitHub ID
    admin= "Wxiaote" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
